<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" Async="true" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Read Aloud Practice</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body onload="pageLoadFunction()">

    <form id="form1" runat="server">
      
        <asp:TextBox ID="TextBox_ReadAloudText" runat="server" TextMode="MultiLine" Height="247px" Width="834px" BorderStyle="Solid">Text box Read Aloud. </asp:TextBox>
                             <br />
             <%--<asp:ScriptManager ID="ScriptManager2" runat="server" EnablePageMethods="true"></asp:ScriptManager>--%>
            <asp:ScriptManager ID="ScriptManager1" runat="server" EnablePageMethods="true" EnablePartialRendering="true" ></asp:ScriptManager>
            <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional" RenderMode="Inline" ChildrenAsTriggers="true">
               <ContentTemplate>
                 <asp:DropDownList ID="DropDownList_ReadAloudRate" runat="server"  AutoPostBack="True" OnSelectedIndexChanged="DropDownList_ReadAloudRate_SelectedIndexChanged"> </asp:DropDownList>
                 <asp:DropDownList ID="DropDownList_MS_VoiceNameOnServer" runat="server" AutoPostBack="True" Height="16px" OnSelectedIndexChanged="DropDownList_MS_VoiceNameOnServer_SelectedIndexChanged" style="margin-top: 0px" Width="327px">
                 </asp:DropDownList>
               </ContentTemplate>
            </asp:UpdatePanel>
        <p>
        </p>
            <br /><br />
        <select id="DropDownList_VoiceOnClient" onchange="DropDownList_Changed_VoiceOnClient()">  <option>Choose a voice</option> </select>
            <br /><br />
           <input type="button" id="ButtonReadAloudOnServer"  onclick ="ReadAloudOnServer()" value="Read Aloud On Server" />
 
    <br /><br />
            <input type="button" id="ButtonReadAloudOnClient"  onclick ="ReadAloudOnClient()" value="Read Aloud On Client" /></form>
    <p>
        <input type="button" id="Button1" value="button" onclick ="test()" /></p>
</body>
</html>


<%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
<script src="JavaScriptFunctions.js"></script>
        <script>
            var browserName = "";
            var textString = "";
            var CharacterPositionStart_arr = new Array();
            var CharacterPositionEnd_arr = new Array();
            var CT_a = []; // text to speech convert time  new Array()
            var CT_a_i = 0; //text to speech convert time array indexing.    
            var CT_a_max_i = 0;
            var CT_aShrinkRatio = 0.7; //manulshrink CT_a[] - time of each word generated by syntheButtonReadAloudOnServersizer on server
            var audioPlayerTimeUpdateInterval;
            var data = [];
            var TextStringLenght;
            var textlen;
            var CharacterPositionStart;
            var characterCount;
            var CharacterPositionEnd;
            var AudioPosition_TimeSpan;
            var words = new Array();
            var wordsIndex = 0;
            var streamData;
            var TextBox_ReadAloudText_id
            var audioPlayer= new Audio();
            var audioPlayerCurrentTimeinCT_aIndex= 0;
            var ct_pre = 0;
            var source = new EventSource('SSEHandler.ashx');
            var loopCount = 0;
            var voicename_Array = new Array();
            var DropDownList_VoiceOnClient_Id = document.getElementById("DropDownList_VoiceOnClient");
            var allVoices;
            var allVoices_index = 0;
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
           var ClientSpeech = new SpeechSynthesisUtterance();
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function pageLoadFunction() {
                browserName = detectBrowser();
                //alert(browserName);
                textString = "This is a moving spectacle, for crowds of people stand on the shore watching the lanterns drifting away until they can be seen no more.";
                TextBox_ReadAloudText_id = document.getElementById("TextBox_ReadAloudText");
                TextBox_ReadAloudText_id.value = textString;
                loadVoices();
            }
                         <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function populateVoiceList() {
                
                allVoices = speechSynthesis.getVoices();
                allVoices.forEach(function (voice, index) {
                    //console.log("myvoice " + index + ": " + voice.name);
                    voicename_Array[index] = voice.name;
                    //var option = $('<option>').val(index).html(voice.name).prop("selected", voice.default);
                    //$('#voices').append(option);
                });

                if (allVoices.length > 0 && speechSynthesis.onvoiceschanged !== undefined) {
                    // unregister event listener (it is fired multiple times)
                    speechSynthesis.onvoiceschanged = null;
                    addVoiceToDropDownList(voicename_Array);
                }

            }
                         <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function loadVoices() {
                
                populateVoiceList();
                if (speechSynthesis.onvoiceschanged !== undefined) {
                    speechSynthesis.onvoiceschanged = populateVoiceList;
                    //speechSynthesis.addEventListener("voiceschanged", function (event) {
                    //},false);
                }

            }
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function addVoiceToDropDownList(arr) {

                var tmp_i = 0;
                var tmp_j = 0;
   
                DropDownList_VoiceOnClient_Id.length = 1;
                DropDownList_VoiceOnClient_Id.options[0].selected = true;
                for (var x = 0; x < arr.length; x++) {
                    var option = document.createElement("option");
                    option.setAttribute("value", x);
                    option.appendChild(document.createTextNode(arr[x]));
                    DropDownList_VoiceOnClient_Id.appendChild(option);
                }
                //DropDownList_VoiceOnClient_Id.options[0].value = 0;
                //DropDownList_VoiceOnClient_Id.options[0].text = arr[0];
                //DropDownList_VoiceOnClient_Id.onchange = mychange();
                //undefined

            }
            function DropDownList_Changed_VoiceOnClient() {
                allVoices_index = DropDownList_VoiceOnClient_Id.selectedIndex;
                console.log(DropDownList_VoiceOnClient_Id.selectedIndex);
            }
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function ReadAloudOnClient() {


                ClientSpeech.addEventListener("end", function (event) {
                    //alert("end ClientSpeech");
                    console.log(event.results)
                },false);
                ClientSpeech.addEventListener("boundary", function (event) {
                    console.log("event.charIndex: " + event.charIndex);
                    TextBox_ReadAloudText_id.setSelectionRange(Number(event.charIndex), Number(event.charIndex) + Number(words[wordsIndex].length));
                    console.log("prop charIndex: " + $('#TextBox_ReadAloudText').prop("selectionStart"));
                    console.log("---------------------------");
                    //console.log("words: "  + words[wordsIndex]);
                    //console.log("wordlength: " + words[wordsIndex].length);
                    
                    wordsIndex++;
                    //var mychar = event.utterance.text.charAt(event.charIndex);
                    //var mychar = event.utterance.text.charIndex(event.charIndex);
                    //console.log(event.results);
                    //event.returnValue
                    //event.char
                    //console.log(event.name + ' boundary reached after ' + event.elapsedTime + ' milliseconds.');
                },false);

                textString = TextBox_ReadAloudText_id.value;
                words = textString.split(" ");
                wordsIndex = 0;
                TextBox_ReadAloudText_id.focus();
                ClientSpeech.voice = allVoices[allVoices_index];
                ClientSpeech.lang = allVoices[allVoices_index].lang;
               ClientSpeech.text = textString;
               window.speechSynthesis.speak(ClientSpeech);



            }

            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function ReadAloudOnServer() {
                loopCount = 0;
                if (TextBox_ReadAloudText_id != null) {
                    TextBox_ReadAloudText_id.focus();
                    var readTextString = TextBox_ReadAloudText_id.value;
                    var readTextLenght = readTextString.length;
                    if (readTextLenght != 0) {
                        CT_a = [];
                        CT_a_i = 0;
                        addEventListener_SSEHandler(readTextLenght)
                        PageMethods.ReadAloudOnServer(readTextString);
                    }
                }
            }

            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
  
            function ConvertTimeSpanStringToSeconds(s) {
                sss = s.split(":");
                s0 = sss[0];
                s1 = sss[1];
                s2 = sss[2];
                return Number(Number(s0 * 3600) + Number(s1 * 60) + Number(s2));
            }
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>

            //$(document).ready(function () {
            //    console.log("ready!");
            //    $("#Button1").click(function () {
            //        addEventListener_SSEHandler(textlen);
            //    });
            //});
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function audioPlayerTimeUpdate() {
                
                loopCount++;
                console.log("loopCount: " + loopCount);
                var ct = audioPlayer.currentTime; // * CT_aShrinkRatio;
                ct_pre = ct
                //console.log("ct: " + ct);
                while ((audioPlayerCurrentTimeinCT_aIndex < CT_a.length) && ((ct) >= CT_a[audioPlayerCurrentTimeinCT_aIndex])) {
                    audioPlayerCurrentTimeinCT_aIndex++;
                }
                if (audioPlayerCurrentTimeinCT_aIndex > 0)
                    audioPlayerCurrentTimeinCT_aIndex = audioPlayerCurrentTimeinCT_aIndex- 1;  //?? -1 ??
                TextBox_ReadAloudText_id.setSelectionRange(Number(CharacterPositionStart_arr[audioPlayerCurrentTimeinCT_aIndex]), Number(CharacterPositionEnd_arr[audioPlayerCurrentTimeinCT_aIndex]));
            }
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function addEventListener_SSEHandler(textlen) {
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
                source.addEventListener("open", function (event) {
                    $('#headerDiv').append('Connection Opened');
                }, false);
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
                source.addEventListener("error", function (event) {
                    if (event.eventPhase == EventSource.CLOSED) {
                        $('#footerDiv').append('Connection Closed!');
                    }
                }, false);
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
                source.addEventListener("message", function (event) {
                }, false);
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
                source.addEventListener("cursorData", function (event) {
                    cursorData = event.data.split(",");
                    CharacterPositionStart = Number(cursorData[0]);
                    characterCount = Number(cursorData[1]);
                    AudioPosition_TimeSpan = cursorData[2];
                    CharacterPositionEnd = CharacterPositionStart + characterCount;

                    CharacterPositionStart_arr[CT_a_i] = CharacterPositionStart;
                    CharacterPositionEnd_arr[CT_a_i] = CharacterPositionEnd;
                    CT_a[CT_a_i] = ConvertTimeSpanStringToSeconds(AudioPosition_TimeSpan);

                    CT_a_max_i = CT_a_i;
                    //console.log("CT_a[CT_a_i]: " + CT_a[CT_a_i]);
                    //console.log("AudioPosition_TimeSpan: " + AudioPosition_TimeSpan);
                    //console.log("CT_a_max_i: " + CT_a_max_i);
                    //console.log("CT_a_i: " + CT_a_i);
                    //var max = TextBox1_Id.scrollHeight;
                    //TextBox1_Id.scrollTop = 0.8 * Number(max) * (Number(CharacterPositionEnd_arr[CT_a_i]) / textlen);

                    CT_a_i++;
                }, false);
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
                source.addEventListener("TextToSpeechBase64StringData", function (event) {
                    base64_string = "";
                    base64_string = event.data;
                    audioPlayer.src = "data:audio/wav;base64," + base64_string;
                    audioPlayerCurrentTimeinCT_aIndex = 0;
                    audioPlayer.load();

                    audioPlayer.addEventListener('loadedmetadata', function () {
                        if (isNaN(audioPlayer.duration))
                            return;
                        if (audioPlayer.duration <= 0)
                            return;
                        if (CT_a.lengh <= 0)
                            return;
                        CT_aShrinkRatio = Number(Number(audioPlayer.duration) / Number(CT_a[CT_a_max_i])); //0.84
                        //CT_aShrinkRatio = Number(Number(CT_a[CT_a_max_i]) / Number(audioPlayer.duration)); //1.1
                        //console.log("CT_a[CT_a_max_i]: " + CT_a[CT_a_max_i]);
                        //console.log("CT_aShrinkRatio: " + CT_aShrinkRatio);
                        for (var tmp = 0; tmp < CT_a.length; tmp++) {
                            CT_a[tmp] = CT_a[tmp] * CT_aShrinkRatio;
                        };

                        audioPlayerTimeUpdateInterval = setInterval(audioPlayerTimeUpdate, 40);
                        //audioPlayerTimeUpdateInterval = setTimeout(audioPlayerTimeUpdate, 40);
                        audioPlayer.play();
                        
                    });
                    //audioPlayer.addEventListener("timeupdate", function () {


                    //    var ct = audioPlayer.currentTime * CT_aShrinkRatio;
                    //    ct_pre = ct
                    //    console.log("audioPlayer.currentTime: " + audioPlayer.currentTime)
                    //    console.log("ct: " + ct);
                    //    while ((audioPlayerCurrentTimeinCT_aIndex < CT_a.length) && ((ct ) >= CT_a[audioPlayerCurrentTimeinCT_aIndex])) {
                    //        audioPlayerCurrentTimeinCT_aIndex++;
                    //    }
                    //    if (audioPlayerCurrentTimeinCT_aIndex > 0)
                    //        audioPlayerCurrentTimeinCT_aIndex = audioPlayerCurrentTimeinCT_aIndex - 1;
                    //    TextBox_ReadAloudText_id.setSelectionRange(Number(CharacterPositionStart_arr[audioPlayerCurrentTimeinCT_aIndex]), Number(CharacterPositionEnd_arr[audioPlayerCurrentTimeinCT_aIndex])); 
               
                    //});  

                    audioPlayer.addEventListener("playing", function(){
                        //console.log("playing: " + audioPlayer.currentTime);
                    });
                    audioPlayer.addEventListener("ended", function () {
                        clearInterval(audioPlayerTimeUpdateInterval);
                        //clearTimeout(audioPlayerTimeUpdateInterval);
                        console.log("ended:" + audioPlayer.currentTime);
                        //alert(audioPlayer.currentTime);
                      
                    });

                }, false);
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
                source.addEventListener("OnSpeakCompleted", function (event) {
                    console.log("OnSpeakCompleted: " + event.data + "\n\n");
                    
                }, false);
             <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            }
            <%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>
            function test() {
                //TextBox_ReadAloudText_id.focus();
                //TextBox_ReadAloudText_id.setSelectionRange(127, 127 + 5);

               
                var cursorPositionStart = $('#TextBox_ReadAloudText').prop("selectionStart");

                console.log(cursorPositionStart);
                //console.log(cursorPositionSEnd);
            }
        </script>
<%--/////////////////////////////////////////////////////////////////////////////////////////////////////--%>    
